name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        run: cargo build --release --target ${{ matrix.os }}${{ matrix.arch }}-unknown-linux-musl

      - name: Calculate next tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version number and tag release
        uses: anothrNick/github-tag-action@v1.19.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag_version.outputs.next_tag }}
          tag_message: "Version ${{ steps.tag_version.outputs.next_tag }}"
          files: "Cargo.toml"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.next_tag }}
          release_name: Release ${{ steps.tag_version.outputs.next_tag }}
          body: |
            Changes in this release:
            - Add feature X
            - Fix bug Y
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/mine
          asset_name: mine-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
