name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build binary
        run: cargo build --release

      - name: Create release tag
        uses: docker://ninjaops/github-tag-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: auto
          commit_sha: ${{ github.sha }}
          tag_prefix: v
          tag_suffix: ""
          message: "Version %VERSION%"
          files: Cargo.toml

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: mine-${{ matrix.os }}
          path: target/release/mine.exe
