name: Build, bump version and create release

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: ./target/release
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-

      - name: Build
        run: cargo build --verbose --release
      - name: Bump version
        run: |
          cargo install cargo-bump
          cargo bump patch --git-commit
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(jq -r '.package.version' Cargo.toml)
          release_name: Release $(jq -r '.package.version' Cargo.toml)
          body: |
            Release for version $(jq -r '.package.version' Cargo.toml)
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/mine.exe
          asset_name: mine.exe
          asset_content_type: application/octet-stream
