name: Build, bump version and create release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        binary_name: ["mine", "mine", "mine"]
        binary_ext: [".exe", "", ""]

    steps:
      - uses: actions/checkout@v3

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: ./target/release
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-

      - name: Build
        run: cargo build --verbose --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./target/release/${{ matrix.binary_name }}${{ matrix.binary_ext }}:${{ matrix.binary_name }}-${{ env.VERSION }}-${{ matrix.os }}-${{ runner.arch }}.tar.gz
