name: Build and Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add target
        run: rustup update

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Build
        run: cargo build --verbose --release

      - name: Package
        run: |
          mkdir -p bin
          cp target/release/mine bin/
          os_name=$(echo ${{ matrix.os }} | sed 's/macos-//;s/10.15/catalina/;s/11/big_sur/;s/12/monterey/')
          arch=$(echo "x86_64-apple-darwin" | cut -d- -f1)
          tar czf mine-${{ github.event.release.tag_name }}.${os_name}.${arch}.bottle.tar.gz -C bin mine

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mine-${{ github.event.release.tag_name }}.${os_name}.${arch}.bottle.tar.gz
          path: mine-${{ github.event.release.tag_name }}.${os_name}.${arch}.bottle.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Calculate checksums and generate table
        run: |
          table="| Filename | SHA256 Checksum |\n|----------|-----------------|\n"
          for file in artifacts/*.tar.gz; do
            checksum=$(sha256sum "$file" | awk '{print $1}')
            table+="| $(basename "$file") | $checksum |\n"
          done
          echo "table=$table" >> $GITHUB_ENV

      - name: Attach binaries to the release
        uses: softprops/action-gh-release@v1
        with:
          files: "artifacts/*.tar.gz"
          body: ${{ env.table }}
